global:
  scrape_interval:     15s
  evaluation_interval: 1m


scrape_configs:
  - job_name: http-monitoring # To get metrics about the exporter’s targets
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - obs:9464                # Target to probe sample app
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9115  # The blackbox exporter’s real hostname:port. For Windows and macOS replace with - host.docker.internal:9115

  - job_name: icmp-monitoring # To get metrics about the exporter’s targets
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
          - obs:9464                # Target to probe sample app
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9115  # The blackbox exporter’s real hostname:port. For Windows and macOS replace with - host.docker.internal:9115

  - job_name: obs-spring
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - obs:9464
